spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parkingdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

jwt:
  secret: DevJwtSecretKeyForParkingApplication123456
  expiration: 86400000
