# ===============================
# Application Info
# ===============================
spring.application.name=parking-bill-generator
spring.profiles.active=dev

# ===============================
# Server Settings
# ===============================
server.port=8080

# ===============================
# Logging
# ===============================
logging.level.root=INFO
logging.level.com.parking.app=INFO

# ===============================
# Swagger / SpringDoc
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
