spring:
  datasource:
    url: jdbc:postgresql://dr-postgres-db.c36sq60wwxgg.us-east-2.rds.amazonaws.com:5432/appdb
    username: postgres
    password: ChangeMe123!

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: false

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

server:
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
